import type { Profile, Locality, Project, Listing, Inquiry, SavedSearch, PropertyType, AssetClass, ListingType, Furnishing, PossessionStatus, Role, VerificationStatus } from './portal';

export const bhkOptions = ["1 BHK", "2 BHK", "3 BHK", "4 BHK", "5+ BHK"];
export const propertyTypes: PropertyType[] = [
  "Apartment",
  "Builder Floor",
  "Villa",
  "Plot",
  "Office Space",
  "Retail Shop",
  "Warehouse",
];
export const amenityOptions = [
  "Clubhouse",
  "Power Backup",
  "Swimming Pool",
  "Gym",
  "EV Charging",
  "24x7 Security",
  "Metro Connectivity",
  "Visitor Parking",
  "Business Lounge",
  "Cafeteria",
  "Loading Bay",
  "Rainwater Harvesting",
];
export const profiles: Profile[] = [
  {
    id: "profile-agent-1",
    slug: "ananya-mehra",
    role: "agent",
    name: "Ananya Mehra",
    phone: "+91 98110 22110",
    email: "ananya@citysblock.in",
    avatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80",
    city: "Gurugram",
    companyName: "Urban Acres Advisory",
    verificationStatus: "verified",
    bio: "Luxury residential specialist for NCR micro-markets with high-conversion site visit pipelines.",
  },
  {
    id: "profile-agent-2",
    slug: "rahul-kapoor",
    role: "agent",
    name: "Rahul Kapoor",
    phone: "+91 98990 77881",
    email: "rahul@citysblock.in",
    avatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80",
    city: "Noida",
    companyName: "Capital Realty Network",
    verificationStatus: "verified",
    bio: "Investor-focused consultant covering Noida Expressway, data-led pricing, and resale velocity.",
  },
  {
    id: "profile-builder-1",
    slug: "altura-homes",
    role: "builder",
    name: "Altura Homes",
    phone: "+91 120 400 8800",
    email: "sales@alturahomes.in",
    avatar:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=600&q=80",
    city: "Bengaluru",
    companyName: "Altura Homes",
    verificationStatus: "verified",
    bio: "Mid-premium developer focused on transit-oriented communities across South India.",
  },
  {
    id: "profile-owner-1",
    slug: "meenal-arora",
    role: "owner",
    name: "Meenal Arora",
    phone: "+91 99713 55442",
    email: "meenal@example.com",
    avatar:
      "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=600&q=80",
    city: "Bengaluru",
    verificationStatus: "pending",
    bio: "Owner listing a small curated portfolio of premium apartments and managed rentals.",
  },
  {
    id: "profile-buyer-1",
    slug: "avi-malhotra",
    role: "buyer",
    name: "Avi Malhotra",
    phone: "+91 98201 70000",
    email: "avi@example.com",
    avatar:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80",
    city: "Mumbai",
    verificationStatus: "verified",
    bio: "Actively exploring end-use and income-generating property in top-tier Indian markets.",
  },
  {
    id: "profile-admin-1",
    slug: "ops-team",
    role: "admin",
    name: "Ops Team",
    phone: "+91 11 4555 7788",
    email: "ops@citysblock.in",
    avatar:
      "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=600&q=80",
    city: "New Delhi",
    companyName: "The City's Block",
    verificationStatus: "verified",
    bio: "Marketplace operations and listing moderation.",
  },
];
export const localities: Locality[] = [
  {
    id: "loc-ahmedabad-bodakdev",
    city: "Ahmedabad",
    slug: "bodakdev",
    displayName: "Bodakdev",
    overview: "Bodakdev is a premium commercial and residential hub in west Ahmedabad with Grade A office buildings and strong connectivity.",
    avgPricePerSqft: 8500,
    rentalYield: "4.2%",
    coordinates: { lat: 23.0469, lng: 72.5060 },
    highlights: ["Premium offices", "Retail hubs", "Metro access"],
    landmarks: ["Akshar Square", "Drive In Road", "Vastrapur Lake"],
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "loc-ahmedabad-ashram-road",
    city: "Ahmedabad",
    slug: "ashram-road",
    displayName: "Ashram Road",
    overview: "Ashram Road is Ahmedabad's established commercial spine with a dense cluster of office buildings and business centres.",
    avgPricePerSqft: 6200,
    rentalYield: "4.8%",
    coordinates: { lat: 23.0225, lng: 72.5714 },
    highlights: ["Business district", "Sun West Bank", "Krupal Pathsala"],
    landmarks: ["Sun West Bank", "Krupal Pathsala", "Yash Anant"],
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "loc-ahmedabad-vastrapur",
    city: "Ahmedabad",
    slug: "vastrapur",
    displayName: "Vastrapur",
    overview: "Vastrapur is a sought-after residential and commercial locality near the lake, popular for furnished offices and upscale bungalows.",
    avgPricePerSqft: 9200,
    rentalYield: "3.9%",
    coordinates: { lat: 23.0395, lng: 72.5290 },
    highlights: ["Vastrapur Lake", "Sheetal Westpark", "Abhishree Adroit"],
    landmarks: ["Vastrapur Lake", "Mansi Circle", "CG Road"],
    image: "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "loc-ahmedabad-science-city",
    city: "Ahmedabad",
    slug: "science-city",
    displayName: "Science City",
    overview: "Science City is a premium bungalow and villa zone in east Ahmedabad with large plot sizes and established green neighbourhoods.",
    avgPricePerSqft: 14000,
    rentalYield: "2.8%",
    coordinates: { lat: 23.0469, lng: 72.5490 },
    highlights: ["Luxury bungalows", "Large plots", "Established area"],
    landmarks: ["Science City Road", "Gulmohar Greens", "Super Bungalow"],
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "loc-gurugram-gcr",
    city: "Gurugram",
    slug: "golf-course-road",
    displayName: "Golf Course Road",
    overview: "Golf Course Road remains a premium NCR corridor with Grade A residences, direct rapid metro access, and sustained end-user demand.",
    avgPricePerSqft: 19500,
    rentalYield: "3.4%",
    coordinates: { lat: 28.4491, lng: 77.1008 },
    highlights: ["Rapid metro connectivity", "Luxury projects", "Corporate catchment"],
    landmarks: ["Sector 42-43 Metro", "DLF Cyber Hub", "Artemis Hospital"],
    image: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "loc-noida-150",
    city: "Noida",
    slug: "sector-150",
    displayName: "Sector 150",
    overview: "Sector 150 is a low-density sports-city micro-market favored by upgraders seeking larger layouts and planned open space.",
    avgPricePerSqft: 11200,
    rentalYield: "2.8%",
    coordinates: { lat: 28.4088, lng: 77.4837 },
    highlights: ["Wide roads", "Sports infrastructure", "Expressway access"],
    landmarks: ["Noida-Greater Noida Expressway", "Shaheed Bhagat Singh Park", "Jewar corridor"],
    image: "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=1200&q=80",
  },
];
export const projects: Project[] = [
  {
    id: "project-azure-heights",
    slug: "azure-heights-residences",
    name: "Azure Heights Residences",
    builderId: "profile-builder-1",
    city: "Noida",
    localitySlug: "sector-150",
    coverImage:
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=1600&q=80",
    ],
    minPrice: 12500000,
    maxPrice: 24500000,
    configurations: ["2 BHK", "3 BHK", "4 BHK"],
    possessionDate: "2028-03-01",
    status: "Under Construction",
    brochureUrl: "#",
    featured: true,
    summary:
      "Sports-centric premium development with club-grade amenities, larger balconies, and skyline-facing towers.",
    amenities: ["Olympic pool", "Sky lounge", "Pickleball court", "Retail arcade"],
  },
  {
    id: "project-sierra-court",
    slug: "sierra-court-signature",
    name: "Sierra Court Signature",
    builderId: "profile-builder-1",
    city: "Bengaluru",
    localitySlug: "whitefield",
    coverImage:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80",
    ],
    minPrice: 9200000,
    maxPrice: 17800000,
    configurations: ["2 BHK", "3 BHK"],
    possessionDate: "2027-11-15",
    status: "New Launch",
    brochureUrl: "#",
    featured: true,
    summary:
      "Metro-adjacent apartment community positioned for tech corridor professionals and rental investors.",
    amenities: ["Business lounge", "Cricket net", "Creche", "Co-working pavilion"],
  },
  {
    id: "project-atrium-one",
    slug: "atrium-one-business-park",
    name: "Atrium One Business Park",
    builderId: "profile-builder-1",
    city: "Mumbai",
    localitySlug: "bkc",
    coverImage:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=80",
    ],
    minPrice: 52000000,
    maxPrice: 145000000,
    configurations: ["800 sq.ft.", "1200 sq.ft.", "5000 sq.ft. floor plates"],
    possessionDate: "2026-12-30",
    status: "Ready to Move",
    brochureUrl: "#",
    featured: false,
    summary:
      "Institutional-ready commercial address with LEED-aligned design, concierge services, and flagship frontage.",
    amenities: ["Board rooms", "Smart access", "Valet parking", "Food court"],
  },
];
export const listings: Listing[] = [
  // ── Ahmedabad Office Rentals (from live data) ──────────────────────────────
  {
    id: "listing-ahm-1",
    slug: "akshar-square-bodakdev-office-1302",
    listingType: "rent",
    assetClass: "commercial",
    propertyType: "Office Space",
    title: "Furnished Office – Akshar Square, Bodakdev Road (13th Floor)",
    description: "1,098 sq.ft. furnished office on the 13th floor of Akshar Square. Includes 1 cabin, 13 workstations, 1 meeting room, pantry, washroom, and reception.",
    city: "Ahmedabad",
    localitySlug: "bodakdev",
    address: "Unit 1302, Akshar Square, Bodakdev Road, Ahmedabad",
    coordinates: { lat: 23.0469, lng: 72.5060 },
    price: 75000,
    priceUnit: "month",
    area: 1098,
    areaUnit: "sqft",
    bhk: null,
    bathrooms: 1,
    furnishing: "Fully Furnished",
    possessionStatus: "Ready to Move",
    ownerType: "agent",
    featured: true,
    verified: true,
    status: "active",
    tags: ["Furnished", "13th Floor", "Bodakdev"],
    amenities: ["Business Lounge", "Visitor Parking", "24x7 Security"],
    images: ["https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=80"],
    profileId: "profile-agent-1",
    postedOn: "2026-04-10",
  },
  {
    id: "listing-ahm-2",
    slug: "sheetal-westpark-vastrapur-b903",
    listingType: "rent",
    assetClass: "commercial",
    propertyType: "Office Space",
    title: "Unfurnished Office – Sheetal Westpark Imperia, Vastrapur Lake (9th Floor)",
    description: "1,000 sq.ft. unfurnished office unit B/903 on the 9th floor of Sheetal Westpark Imperia, overlooking Vastrapur Lake.",
    city: "Ahmedabad",
    localitySlug: "vastrapur",
    address: "Unit B/903, Sheetal Westpark Imperia, Vastrapur Lake, Ahmedabad",
    coordinates: { lat: 23.0395, lng: 72.5290 },
    price: 50000,
    priceUnit: "month",
    area: 1000,
    areaUnit: "sqft",
    bhk: null,
    bathrooms: 1,
    furnishing: "Unfurnished",
    possessionStatus: "Ready to Move",
    ownerType: "agent",
    featured: false,
    verified: true,
    status: "active",
    tags: ["Unfurnished", "Lake View", "Vastrapur"],
    amenities: ["Visitor Parking", "24x7 Security"],
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80"],
    profileId: "profile-agent-1",
    postedOn: "2026-05-06",
  },
  {
    id: "listing-ahm-3",
    slug: "sheetal-westpark-vastrapur-a906",
    listingType: "rent",
    assetClass: "commercial",
    propertyType: "Office Space",
    title: "Furnished Office – Sheetal Westpark Imperia, Vastrapur Lake (9th Floor)",
    description: "875 sq.ft. furnished office unit A/906 with 2 cabins, 9 workstations, 1 meeting room, pantry, washroom, and reception.",
    city: "Ahmedabad",
    localitySlug: "vastrapur",
    address: "Unit A/906, Sheetal Westpark Imperia, Vastrapur Lake, Ahmedabad",
    coordinates: { lat: 23.0395, lng: 72.5290 },
    price: 50000,
    priceUnit: "month",
    area: 875,
    areaUnit: "sqft",
    bhk: null,
    bathrooms: 1,
    furnishing: "Fully Furnished",
    possessionStatus: "Ready to Move",
    ownerType: "agent",
    featured: true,
    verified: true,
    status: "active",
    tags: ["Furnished", "Lake View", "Vastrapur"],
    amenities: ["Business Lounge", "Visitor Parking", "24x7 Security"],
    images: ["https://images.unsplash.com/photo-1497366412874-3415097a27e7?auto=format&fit=crop&w=1600&q=80"],
    profileId: "profile-agent-1",
    postedOn: "2026-04-06",
  },
  {
    id: "listing-ahm-4",
    slug: "abhishree-adroit-vastrapur-802",
    listingType: "rent",
    assetClass: "commercial",
    propertyType: "Office Space",
    title: "Semi-Furnished Office – Abhishree Adroit, Vastrapur Mansi Circle (8th Floor)",
    description: "1,005 sq.ft. semi-furnished office unit 802 with 2 cabins, 12 workstations, pantry, washroom, and reception.",
    city: "Ahmedabad",
    localitySlug: "vastrapur",
    address: "Unit 802, Abhishree Adroit, Vastrapur Mansi Circle, Ahmedabad",
    coordinates: { lat: 23.0380, lng: 72.5310 },
    price: 37000,
    priceUnit: "month",
    area: 1005,
    areaUnit: "sqft",
    bhk: null,
    bathrooms: 1,
    furnishing: "Semi-Furnished",
    possessionStatus: "Ready to Move",
    ownerType: "agent",
    featured: false,
    verified: true,
    status: "active",
    tags: ["Semi-Furnished", "Mansi Circle"],
    amenities: ["Visitor Parking", "24x7 Security"],
    images: ["https://images.unsplash.com/photo-1517502166878-35c93a0072f0?auto=format&fit=crop&w=1600&q=80"],
    profileId: "profile-agent-2",
    postedOn: "2026-05-05",
  },
  {
    id: "listing-ahm-5",
    slug: "sun-west-bank-ashram-road-1st-floor",
    listingType: "rent",
    assetClass: "commercial",
    propertyType: "Office Space",
    title: "Large Unfurnished Floor – Sun West Bank, Ashram Road (1st Floor)",
    description: "1,850 sq.ft. unfurnished office space on the 1st floor of Sun West Bank, Ashram Road. Ideal for large teams.",
    city: "Ahmedabad",
    localitySlug: "ashram-road",
    address: "1st Floor, Sun West Bank, Ashram Road, Ahmedabad",
    coordinates: { lat: 23.0225, lng: 72.5714 },
    price: 139000,
    priceUnit: "month",
    area: 1850,
    areaUnit: "sqft",
    bhk: null,
    bathrooms: 2,
    furnishing: "Unfurnished",
    possessionStatus: "Ready to Move",
    ownerType: "agent",
    featured: true,
    verified: true,
    status: "active",
    tags: ["Large Floor", "Ashram Road", "13 Floors"],
    amenities: ["Visitor Parking", "24x7 Security", "Power Backup"],
    images: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=80"],
    profileId: "profile-agent-1",
    postedOn: "2026-03-07",
  },
  {
    id: "listing-ahm-6",
    slug: "sun-west-bank-ashram-road-furnished-5th",
    listingType: "rent",
    assetClass: "commercial",
    propertyType: "Office Space",
    title: "Furnished Office – Sun West Bank, Ashram Road (5th Floor)",
    description: "770 sq.ft. furnished office on the 5th floor with 2 cabins, 7 workstations, 1 meeting room, pantry, washroom, and reception.",
    city: "Ahmedabad",
    localitySlug: "ashram-road",
    address: "5th Floor, Sun West Bank, Ashram Road, Ahmedabad",
    coordinates: { lat: 23.0225, lng: 72.5714 },
    price: 49000,
    priceUnit: "month",
    area: 770,
    areaUnit: "sqft",
    bhk: null,
    bathrooms: 1,
    furnishing: "Fully Furnished",
    possessionStatus: "Ready to Move",
    ownerType: "agent",
    featured: true,
    verified: true,
    status: "active",
    tags: ["Furnished", "5th Floor", "Ashram Road"],
    amenities: ["Business Lounge", "Visitor Parking", "24x7 Security"],
    images: ["https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1600&q=80"],
    profileId: "profile-agent-1",
    postedOn: "2026-03-24",
  },
  {
    id: "listing-ahm-7",
    slug: "world-center-ashram-road-dinesh-hall",
    listingType: "rent",
    assetClass: "commercial",
    propertyType: "Office Space",
    title: "Premium Furnished Office – World Center, Ashram Road (5th Floor)",
    description: "5,000 sq.ft. fully furnished office at World Center, Dinesh Hall. Features 4 cabins, 100 workstations, 2 meeting rooms, pantry, washroom, and reception.",
    city: "Ahmedabad",
    localitySlug: "ashram-road",
    address: "Unit 504, World Center, Ashram Road Dinesh Hall, Ahmedabad",
    coordinates: { lat: 23.0230, lng: 72.5720 },
    price: 400000,
    priceUnit: "month",
    area: 5000,
    areaUnit: "sqft",
    bhk: null,
    bathrooms: 4,
    furnishing: "Fully Furnished",
    possessionStatus: "Ready to Move",
    ownerType: "agent",
    featured: true,
    verified: true,
    status: "active",
    tags: ["Premium", "Large Team", "Fully Furnished"],
    amenities: ["Business Lounge", "Cafeteria", "Visitor Parking", "24x7 Security"],
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80"],
    profileId: "profile-agent-1",
    postedOn: "2026-03-19",
  },
  {
    id: "listing-ahm-8",
    slug: "krupal-pathsala-ashram-road-12th-floor",
    listingType: "rent",
    assetClass: "commercial",
    propertyType: "Office Space",
    title: "Large Semi-Furnished Floor – Krupal Pathsala, Ashram Road (12th Floor)",
    description: "6,000 sq.ft. semi-furnished office spanning units 1215–1217 on the 12th floor. Includes 3 cabins, 115 workstations, 1 meeting room, pantry, 5 washrooms, and reception.",
    city: "Ahmedabad",
    localitySlug: "ashram-road",
    address: "Units 1215–1217, Krupal Pathsala, Ashram Road, Ahmedabad",
    coordinates: { lat: 23.0220, lng: 72.5710 },
    price: 250000,
    priceUnit: "month",
    area: 6000,
    areaUnit: "sqft",
    bhk: null,
    bathrooms: 5,
    furnishing: "Semi-Furnished",
    possessionStatus: "Ready to Move",
    ownerType: "agent",
    featured: true,
    verified: true,
    status: "active",
    tags: ["Large Floor", "12th Floor", "Ashram Road"],
    amenities: ["Business Lounge", "Visitor Parking", "24x7 Security", "Power Backup"],
    images: ["https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=1600&q=80"],
    profileId: "profile-agent-2",
    postedOn: "2026-03-03",
  },
  {
    id: "listing-ahm-9",
    slug: "nakshatra-regalia-gift-city-16th",
    listingType: "rent",
    assetClass: "commercial",
    propertyType: "Office Space",
    title: "Unfurnished Office – Nakshatra Regalia, GIFT City (16th Floor)",
    description: "2,360 sq.ft. unfurnished office on the 16th floor of Nakshatra Regalia, Gandhinagar GIFT City. Premium address for financial and fintech firms.",
    city: "Ahmedabad",
    localitySlug: "ashram-road",
    address: "16th Floor, Nakshatra Regalia, Gandhinagar GIFT City",
    coordinates: { lat: 23.1500, lng: 72.6800 },
    price: 165000,
    priceUnit: "month",
    area: 2360,
    areaUnit: "sqft",
    bhk: null,
    bathrooms: 2,
    furnishing: "Unfurnished",
    possessionStatus: "Ready to Move",
    ownerType: "agent",
    featured: false,
    verified: true,
    status: "active",
    tags: ["GIFT City", "Fintech Hub", "16th Floor"],
    amenities: ["Visitor Parking", "24x7 Security", "Power Backup"],
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80"],
    profileId: "profile-agent-2",
    postedOn: "2026-04-18",
  },
  // ── Ahmedabad Bungalow Sales (from live data) ──────────────────────────────
  {
    id: "listing-ahm-10",
    slug: "sentossa-greenland-bhadaj-3bhk-a97",
    listingType: "sale",
    assetClass: "residential",
    propertyType: "Villa",
    title: "3 BHK Bungalow – Sentossa Greenland, Bhadaj Circle",
    description: "880 sq.ft. plot, 300 sq.ft. construction. Semi-furnished 3 BHK bungalow in Sentossa Greenland with garden area. 10+ years old.",
    city: "Ahmedabad",
    localitySlug: "bodakdev",
    address: "A/97, Sentossa Greenland, Bhadaj Circle, Ahmedabad",
    coordinates: { lat: 23.0550, lng: 72.5100 },
    price: 90000000,
    priceUnit: "total",
    area: 880,
    areaUnit: "sqft",
    bhk: 3,
    bathrooms: 3,
    furnishing: "Semi-Furnished",
    possessionStatus: "Ready to Move",
    ownerType: "owner",
    featured: true,
    verified: true,
    status: "active",
    tags: ["Bungalow", "Garden", "Bhadaj"],
    amenities: ["Visitor Parking", "24x7 Security"],
    images: ["https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=1600&q=80"],
    profileId: "profile-owner-1",
    postedOn: "2026-04-01",
  },
  {
    id: "listing-ahm-11",
    slug: "super-bungalow-science-city-6bhk",
    listingType: "sale",
    assetClass: "residential",
    propertyType: "Villa",
    title: "6 BHK Super Bungalow – Science City, Ahmedabad",
    description: "625 sq.ft. plot, 500 sq.ft. construction. Furnished 6 BHK bungalow in Science City. 15 years old, premium location.",
    city: "Ahmedabad",
    localitySlug: "science-city",
    address: "Units 1 & 2, Science City Road, Ahmedabad",
    coordinates: { lat: 23.0469, lng: 72.5490 },
    price: 125100000,
    priceUnit: "total",
    area: 625,
    areaUnit: "sqft",
    bhk: 6,
    bathrooms: 6,
    furnishing: "Fully Furnished",
    possessionStatus: "Ready to Move",
    ownerType: "owner",
    featured: true,
    verified: true,
    status: "active",
    tags: ["Luxury", "6 BHK", "Science City"],
    amenities: ["Swimming Pool", "Gym", "24x7 Security", "Visitor Parking"],
    images: ["https://images.unsplash.com/photo-1502005097973-6a7082348e28?auto=format&fit=crop&w=1600&q=80"],
    profileId: "profile-owner-1",
    postedOn: "2026-04-01",
  },
  {
    id: "listing-ahm-12",
    slug: "gulmohar-greens-science-city-4bhk",
    listingType: "sale",
    assetClass: "residential",
    propertyType: "Villa",
    title: "4 BHK Bungalow – Gulmohar Greens, Science City",
    description: "416 sq.ft. plot, 667 sq.ft. construction. Unfurnished 4 BHK bungalow in Gulmohar Greens, Science City. 5+ years old.",
    city: "Ahmedabad",
    localitySlug: "science-city",
    address: "Plot 15, Gulmohar Greens, Science City, Ahmedabad",
    coordinates: { lat: 23.0475, lng: 72.5495 },
    price: 80000000,
    priceUnit: "total",
    area: 416,
    areaUnit: "sqft",
    bhk: 4,
    bathrooms: 4,
    furnishing: "Unfurnished",
    possessionStatus: "Ready to Move",
    ownerType: "owner",
    featured: false,
    verified: true,
    status: "active",
    tags: ["Bungalow", "4 BHK", "Science City"],
    amenities: ["Visitor Parking", "24x7 Security"],
    images: ["https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1600&q=80"],
    profileId: "profile-owner-1",
    postedOn: "2026-04-06",
  },
  {
    id: "listing-ahm-13",
    slug: "hariharashray-sb-thaltej-6bhk",
    listingType: "sale",
    assetClass: "residential",
    propertyType: "Villa",
    title: "6 BHK Furnished Bungalow – Hariharashray, SB Thaltej Road",
    description: "711 sq.ft. plot, 750 sq.ft. construction. G+3 furnished bungalow with garden, servant room, south-facing. 20 years old.",
    city: "Ahmedabad",
    localitySlug: "vastrapur",
    address: "Plot 1, Hariharashray, SB Thaltej Road, Ahmedabad",
    coordinates: { lat: 23.0520, lng: 72.5200 },
    price: 160000000,
    priceUnit: "total",
    area: 711,
    areaUnit: "sqft",
    bhk: 6,
    bathrooms: 6,
    furnishing: "Fully Furnished",
    possessionStatus: "Ready to Move",
    ownerType: "owner",
    featured: true,
    verified: true,
    status: "active",
    tags: ["G+3", "Garden", "South Facing", "Thaltej"],
    amenities: ["Swimming Pool", "24x7 Security", "Visitor Parking"],
    images: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=80"],
    profileId: "profile-owner-1",
    postedOn: "2026-04-01",
  },
  // ── Existing listings ──────────────────────────────────────────────────────
  {
    id: "listing-1",
    slug: "4-bhk-apartment-golf-course-road-gurugram",
    listingType: "sale",
    assetClass: "residential",
    propertyType: "Apartment",
    title: "4 BHK luxury apartment with Aravalli-facing deck",
    description: "A verified premium residence with double-height arrival lobby, semi-private lift landing, modular kitchen, and clubhouse access minutes from corporate Gurugram.",
    city: "Gurugram",
    localitySlug: "golf-course-road",
    address: "Sector 54, Golf Course Road, Gurugram",
    coordinates: { lat: 28.4391, lng: 77.1017 },
    price: 58500000,
    priceUnit: "total",
    area: 3150,
    areaUnit: "sqft",
    bhk: 4,
    bathrooms: 5,
    furnishing: "Semi-Furnished",
    possessionStatus: "Ready to Move",
    ownerType: "agent",
    featured: true,
    verified: true,
    status: "active",
    tags: ["Verified", "Featured", "Corner unit"],
    amenities: ["Clubhouse", "Swimming Pool", "Gym", "24x7 Security", "EV Charging"],
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1600&q=80",
    ],
    profileId: "profile-agent-1",
    postedOn: "2026-03-11",
  },
  {
    id: "listing-4",
    slug: "grade-a-office-space-bkc-mumbai",
    listingType: "rent",
    assetClass: "commercial",
    propertyType: "Office Space",
    title: "Plug-and-play Grade A office suite in BKC",
    description: "Fully fitted commercial suite with reception, cabins, board room, and premium frontage in Mumbai's top institutional office district.",
    city: "Mumbai",
    localitySlug: "bkc",
    address: "Bandra Kurla Complex, Mumbai",
    coordinates: { lat: 19.0677, lng: 72.8701 },
    price: 640000,
    priceUnit: "month",
    area: 2800,
    areaUnit: "sqft",
    bhk: null,
    bathrooms: 2,
    furnishing: "Fully Furnished",
    possessionStatus: "Ready to Move",
    ownerType: "builder",
    featured: true,
    verified: true,
    status: "active",
    tags: ["Commercial", "Ready office"],
    amenities: ["Business Lounge", "Visitor Parking", "24x7 Security", "Cafeteria"],
    images: [
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80",
    ],
    profileId: "profile-builder-1",
    postedOn: "2026-03-20",
  },
];
export const inquiries: Inquiry[] = [
  {
    id: "inq-1",
    listingId: "listing-1",
    listingTitle: "4 BHK luxury apartment with Aravalli-facing deck",
    buyerName: "Avi Malhotra",
    buyerPhone: "+91 98201 70000",
    buyerEmail: "avi@example.com",
    message: "Need a weekend site visit and payment-plan breakup.",
    createdAt: "2026-03-23T11:00:00.000Z",
    channel: "form",
    status: "new",
  },
  {
    id: "inq-2",
    listingId: "listing-4",
    listingTitle: "Plug-and-play Grade A office suite in BKC",
    buyerName: "Richa Sood",
    buyerPhone: "+91 98188 09876",
    buyerEmail: "richa@startup.in",
    message: "Looking for 30 seats with immediate move-in.",
    createdAt: "2026-03-22T08:30:00.000Z",
    channel: "email",
    status: "contacted",
  },
];
export const savedSearches: SavedSearch[] = [
  {
    id: "saved-1",
    label: "Premium 3 BHK in Noida",
    city: "Noida",
    filters: { city: "Noida", bhk: "3 BHK", listingType: "sale" },
    resultCount: 14,
  },
  {
    id: "saved-2",
    label: "Commercial rentals in Mumbai",
    city: "Mumbai",
    filters: { city: "Mumbai", assetClass: "commercial", listingType: "rent" },
    resultCount: 6,
  },
];
